// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mailX.Data;

#nullable disable

namespace mailX.Migrations
{
    [DbContext(typeof(MailXDbContext))]
    [Migration("20260120081558_AddCalendarTables")]
    partial class AddCalendarTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("mailX.Models.AISetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AISettings");
                });

            modelBuilder.Entity("mailX.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConverterUsed")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmailId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkdownContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkdownPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFile")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConversionStatus")
                        .HasDatabaseName("IX_Attachment_ConversionStatus");

                    b.HasIndex("EmailId")
                        .HasDatabaseName("IX_Attachment_EmailId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("mailX.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Attendees")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyContentType")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalendarId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalendarName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ICalUId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Importance")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocalOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnlineMeeting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReminderOn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OnlineMeetingProvider")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("OnlineMeetingUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizerName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OriginalEndTimeZone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OriginalStartTimeZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrencePattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceRange")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReminderMinutesBeforeStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseStatus")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sensitivity")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesMasterId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShowAs")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebLink")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GraphId")
                        .HasDatabaseName("IX_CalendarEvent_GraphId");

                    b.HasIndex("ICalUId")
                        .HasDatabaseName("IX_CalendarEvent_ICalUId");

                    b.HasIndex("SeriesMasterId")
                        .HasDatabaseName("IX_CalendarEvent_SeriesMasterId");

                    b.HasIndex("StartDateTime")
                        .HasDatabaseName("IX_CalendarEvent_StartDateTime");

                    b.HasIndex("AccountEmail", "CalendarId")
                        .HasDatabaseName("IX_CalendarEvent_AccountEmail_CalendarId");

                    b.HasIndex("AccountEmail", "StartDateTime")
                        .HasDatabaseName("IX_CalendarEvent_AccountEmail_StartDateTime");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("mailX.Models.CalendarSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalendarId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalendarName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeltaLink")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastSyncAddedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastSyncDeletedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastSyncUpdatedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountEmail", "CalendarId")
                        .IsUnique()
                        .HasDatabaseName("IX_CalendarSyncState_AccountEmail_CalendarId");

                    b.ToTable("CalendarSyncStates");
                });

            modelBuilder.Entity("mailX.Models.ContractInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmailId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRemote")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ManMonth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmailId")
                        .IsUnique()
                        .HasDatabaseName("IX_ContractInfo_EmailId");

                    b.ToTable("ContractInfos");
                });

            modelBuilder.Entity("mailX.Models.ConverterSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedConverter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Extension")
                        .IsUnique()
                        .HasDatabaseName("IX_ConverterSetting_Extension");

                    b.ToTable("ConverterSettings");
                });

            modelBuilder.Entity("mailX.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bcc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagStatus")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAttachments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Importance")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternetMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNonBusiness")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStarred")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("MyPosition")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentFolderId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PinnedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriorityLevel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PriorityScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReceivedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryOneline")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrgencyLevel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountEmail")
                        .HasDatabaseName("IX_Email_AccountEmail");

                    b.HasIndex("AnalysisStatus")
                        .HasDatabaseName("IX_Email_AnalysisStatus");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("IX_Email_ConversationId");

                    b.HasIndex("InternetMessageId")
                        .HasDatabaseName("IX_Email_InternetMessageId");

                    b.HasIndex("ParentFolderId")
                        .HasDatabaseName("IX_Email_ParentFolderId");

                    b.HasIndex("ReceivedDateTime")
                        .HasDatabaseName("IX_Email_ReceivedDateTime");

                    b.HasIndex("InternetMessageId", "ParentFolderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Email_InternetMessageId_ParentFolderId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("mailX.Models.Folder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("FavoriteOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentFolderId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnreadItemCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountEmail")
                        .HasDatabaseName("IX_Folder_AccountEmail");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("mailX.Models.OneNotePage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LinkedEmailId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OneNotePages");
                });

            modelBuilder.Entity("mailX.Models.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PromptKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Prompt_PromptKey");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("mailX.Models.PromptTestHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExecutionTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputData")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputResult")
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Tokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.ToTable("PromptTestHistories");
                });

            modelBuilder.Entity("mailX.Models.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlainTextContent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("mailX.Models.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeltaLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountEmail", "FolderId")
                        .IsUnique()
                        .HasDatabaseName("IX_SyncState_AccountEmail_FolderId");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("mailX.Models.TeamsMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromUser")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LinkedEmailId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TeamsMessages");
                });

            modelBuilder.Entity("mailX.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmailId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("mailX.Models.Attachment", b =>
                {
                    b.HasOne("mailX.Models.Email", "Email")
                        .WithMany("Attachments")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("mailX.Models.ContractInfo", b =>
                {
                    b.HasOne("mailX.Models.Email", "Email")
                        .WithOne("ContractInfo")
                        .HasForeignKey("mailX.Models.ContractInfo", "EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("mailX.Models.PromptTestHistory", b =>
                {
                    b.HasOne("mailX.Models.Prompt", "Prompt")
                        .WithMany("TestHistories")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("mailX.Models.Todo", b =>
                {
                    b.HasOne("mailX.Models.Email", "Email")
                        .WithMany("Todos")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("mailX.Models.Email", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ContractInfo");

                    b.Navigation("Todos");
                });

            modelBuilder.Entity("mailX.Models.Prompt", b =>
                {
                    b.Navigation("TestHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
